version: '3'

services:
    mongodb:
        image: mongo:4.4.5
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: pass

    postgres:
        image: postgres:13.2-alpine
        ports:
            - 5444:5432
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    tweet_collector:
        build: twitter/
        depends_on:
            - mongodb
    
    etl:
        build: etl/
        depends_on:
            - mongodb
            - postgres